[tool.poetry]
name = "hackaton2023"
version = "0.1.0"
description = ""
authors = ["Daniel Sliwowicz <danielsl@campus.technion.ac.il>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
